### ISSUE TITLE
Tutorial code produces `TypeError: Cannot read property '_iid' of null`

### ISSUE THREAD

**Issue by lazyBisa** [sendbird/SendBird-JavaScript#125]
JavaScript noob here. Sorry, if im doing something fundamentally wrong, please tell me.

I would expect the following code, taken from the [JS tutorial](https://docs.sendbird.com/javascript), to log my application id:
```sh
$ npm install sendbird
$ npm install form-data
$ echo "const SendBird = require('sendbird');
  var sb = new SendBird({appId: 'AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA'});
  console.log(sb.getApplicationId());" | node
```

But I get following error on sb.getApplicationId().
```
TypeError: Cannot read property '_iid' of null
    at Function.value (C:\..\Projects\sendbird\node_modules\sendbird\SendBird.min.js:6:5338)
    at u.value (C:\..\Projects\sendbird\node_modules\sendbird\SendBird.min.js:6:248033)
    at [stdin]:3:16
    at Script.runInThisContext (vm.js:131:20)
    at Object.runInThisContext (vm.js:297:38)
    at Object.<anonymous> ([stdin]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:207:5)
```

Same happens when attempting to `sb.connect(…)`.  
I am also quite puzzled why I have to manually add form-data to my dependencies.

Thanks for your help. All I am looking to do is have a cli-esque experience where I can play around with sendbird from a user-perspective to get a feeling for what is possible with sendbird.

`node --version`: `v14.2.0`

**Comment by lazyBisa** [comment]
sorry, this was meant to go to the SDK repo, not the Sample repo.
see [SendBird-SDK-JavaScript#148](https://github.com/sendbird/SendBird-SDK-JavaScript/issues/148)
